CC = gcc
CFLAGS = -Wextra -Wall -Wvla -std=c99
LDFLAGS = -lm
SRC = cipher.c tests.c main.c
OBJ = $(SRC:.c=.o)
EXEC = cipher

all: $(EXEC)

$(EXEC): $(OBJ)
	$(CC) -o $@ $^ $(LDFLAGS)

%.o: %.c
	$(CC) -o $@ -c $< $(CFLAGS)

clean:
	rm -f $(OBJ)
	rm -f $(EXEC)

.PHONY: all clean
